service: jnlp-lambdas
frameworkVersion: ">=2.0.0 <3.0.0"

provider:
  name: aws
  region: ${opt:region, env:AWS_REGION, 'us-east-2'}
  stage: ${self:custom.stage}
  deploymentBucket:
    blockPublicAccess: true
  timeout: 300 # could be set to the max of 900s (15 mins)
  logRetentionInDays: 7
  environment:
    HOME_DIR: "/tmp"
  tags:
    type: jnlp-agent

custom:
  stage: ${opt:stage, env:STAGE, 'v1'}

functions:
  agentGoContainer:
    name: jnlp-agent-java-container
    image: ${opt:image}